[package]
name = "hsbox"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.32", features = ["derive"] }
openssl = "0.10"
protobuf = "3"
hex = "0.4.3"
